export const icons = {
  leaderboardMenuIconActive: require('./leaderboardMenuIconActive.svg'),
  leaderboardMenuIcon: require('./leaderboardMenuIcon.svg'),
  gamePropsActive: require('./gamePropsActive.svg'),
  gameProps: require('./gameProps.svg'),
  liveGamesActive: require('./liveGamesActive.svg'),
  liveGames: require('./liveGames.svg'),
  accountActive: require('./betsActive.svg'),
  account: require('./bets.svg'),
  playerProps: require('./playerProps.svg'),
  playerPropsActive: require('./playerPropsActive.svg'),
  filter: require('./filter.svg'),
  NBA: require('./NBA.svg'),
  MLB: require('./MLB.svg'),
  NFL: require('./NFL.svg'),
  NHL: require('./NHL.svg'),
  WNBA: require('./WNBA.svg'),
  LClogo: require('./LClogo.svg'),
  draftKingsLogo: require('./draftKingsLogo.svg'),
  bullLogo: require('./bullLogo.svg'),
  fanDuel: require('./fanDuel.svg'),
  emptyFilterArrow: require('./emptyFilterArrow.svg'),
  betsText: require('./betsText.svg'),
  goatedText: require('./goatedText.svg'),
  goatedLogo: require('./goatedLogo.svg'),
  shareBetsWords: require('./shareBetsWords.svg'),
  goPremiumWords: require('./goPremiumWords.svg'),
  betSmarterWords: require('./betSmarterWords.svg'),
  trackBetsWords: require('./trackBetsWords.svg'),
  yellowCheckmarkCircle: require('./yellowCheckmarkCircle.svg'),
  draftKingsSyncLogo: require('./draftKingsSyncLogo.svg'),
  fanDuelSyncLogo: require('./fanDuelSyncLogo.svg')
};
export type IconTypes = keyof typeof icons;
